fix(compile): use APT_FILE_MANIFEST

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -9,6 +9,6 @@ if [ -f "$1/${APT_FILE_MANIFEST}" ]; then
   echo "Apt"
   exit 0
 else
-  echo "Could not find an 'Aptfile'! Please ensure it exists and is checked into Git." >&2
+  echo "Could not find an '${APT_FILE_MANIFEST}'! Please ensure it exists and is checked into Git." >&2
   exit 1
 fi
